[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1

[[plugins]]
repo = 'roxma/vim-yarp'
if = '!has("nvim")'
on_i = 1

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = '!has("nvim")'
on_i = 1

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1

[[plugins]]
repo = 'Shougo/neocomplete'
if = 'has("lua")'
on_i = 1



